#String methods
a=(input())
print(a.upper())
print(a.lower())
print(a.isupper())
print(a.islower())
print(a.isalpha())
print(a.isnumeric())
print(a.isdigit())
print(a.isalnum())
print(a.replace('a','w'))
print(a.split())
print(a.split('a'))
print(a.istitle())
print(a.title())
print(a.capitalize())
print(a.strip())
print(a.swapcase())